name: data_tools

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.12
  - pip>=25.0.0

  - numpy>=1.26.2
  - pandas>=2.1.0
  - matplotlib>=3.7.2
  - seaborn>=0.12.2
  - scikit-learn>=1.5.0
  - scipy>=1.11.2
  - imbalanced-learn>=0.11.0
  - geopandas>=1.0.0
  - h5py>=3.10.0
  - fiona>=1.8.22,<2.0.0
  - shapely>=2.0.2
  - tqdm>=4.65.0
  - pyarrow>=14.0.1
  - rasterio>=1.3.8
  - xarray>=2025.8.0

  - notebook>=7.0.0
  - ipykernel>=6.0.0

  - opencv>=4.0.0
  - pillow>=11.0.0

  - lxml>=5.0.0

  - ruff>=0.12.11
  - pytest>=8.4.0
  - pre-commit>=4.3.0